load("//lib:compile_time.bzl", "aoc_compile_time_binary")

aoc_compile_time_binary(
    name = "main",
    srcs = ["main.cc"],
)

#cc_binary(
    #name = "main",
    #srcs = ["main.cc", ":input_header.h"],
#)

#inline_as_header(
    #name = "input_header",
    #input_file = "input.txt"
#)

